-- Human-readable mirror of the DDL generated by src/db/initSchema.ts.
-- Regenerate after changing src/scoring/categories.ts or the schema statements.

CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    username VARCHAR(64) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role ENUM('admin', 'judge') NOT NULL,
    has_submitted TINYINT(1) NOT NULL DEFAULT 0,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    password_changed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_username (username),
    KEY idx_role (role)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS teams (
    team_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    team VARCHAR(64) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (team_id),
    UNIQUE KEY uq_team (team)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS contestants (
    cand_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    cand_number VARCHAR(8) NOT NULL,
    cand_name VARCHAR(128) NOT NULL,
    team_id INT UNSIGNED NOT NULL,
    cand_gender ENUM('male', 'female', 'other') NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (cand_id),
    UNIQUE KEY uq_cand_number (cand_number),
    KEY idx_team (team_id),
    CONSTRAINT fk_contestant_team FOREIGN KEY (team_id) REFERENCES teams (team_id) ON DELETE RESTRICT
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS scores_vocal (
    score_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    judge_id INT UNSIGNED NOT NULL,
    cand_id INT UNSIGNED NOT NULL,
    voice_tone_quality DECIMAL(5,2) NOT NULL,
    mastery_and_timing DECIMAL(5,2) NOT NULL,
    vocal_expression DECIMAL(5,2) NOT NULL,
    diction DECIMAL(5,2) NOT NULL,
    stage_presence DECIMAL(5,2) NOT NULL,
    entertainment_value DECIMAL(5,2) NOT NULL,
    total_score DECIMAL(6,2) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (score_id),
    UNIQUE KEY uq_judge_subject (judge_id, cand_id),
    KEY idx_subject (cand_id),
    CONSTRAINT fk_vocal_judge FOREIGN KEY (judge_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_vocal_subject FOREIGN KEY (cand_id)
      REFERENCES contestants (cand_id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS scores_interpretative (
    score_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    judge_id INT UNSIGNED NOT NULL,
    team_id INT UNSIGNED NOT NULL,
    originality DECIMAL(5,2) NOT NULL,
    mastery_of_steps DECIMAL(5,2) NOT NULL,
    choreography_and_style DECIMAL(5,2) NOT NULL,
    costume_and_props DECIMAL(5,2) NOT NULL,
    stage_presence DECIMAL(5,2) NOT NULL,
    total_score DECIMAL(6,2) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (score_id),
    UNIQUE KEY uq_judge_subject (judge_id, team_id),
    KEY idx_subject (team_id),
    CONSTRAINT fk_interpretative_judge FOREIGN KEY (judge_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_interpretative_subject FOREIGN KEY (team_id)
      REFERENCES teams (team_id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS scores_modern (
    score_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    judge_id INT UNSIGNED NOT NULL,
    team_id INT UNSIGNED NOT NULL,
    mastery_of_steps DECIMAL(5,2) NOT NULL,
    choreography_and_style DECIMAL(5,2) NOT NULL,
    costume_and_props DECIMAL(5,2) NOT NULL,
    stage_presence DECIMAL(5,2) NOT NULL,
    audience_impact DECIMAL(5,2) NOT NULL,
    total_score DECIMAL(6,2) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (score_id),
    UNIQUE KEY uq_judge_subject (judge_id, team_id),
    KEY idx_subject (team_id),
    CONSTRAINT fk_modern_judge FOREIGN KEY (judge_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_modern_subject FOREIGN KEY (team_id)
      REFERENCES teams (team_id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS activity_logs (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id INT UNSIGNED NULL,
    username VARCHAR(64) NOT NULL DEFAULT '',
    action VARCHAR(64) NOT NULL,
    details VARCHAR(512) NOT NULL DEFAULT '',
    ip VARCHAR(64) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_created_at (created_at),
    KEY idx_user_id (user_id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
